video:
  fps: 24
  seconds: 6
  height: 720
  width: 720
  orbit_degrees: 360
  fov_deg: 45.0
  cam_radius: 3.5
  up: [0, 1, 0]
  lookat: [0, 0, 0]
  elevation_deg: 15

validation:
  clip_model: "ViT-L-14"
  clip_pretrained: "openai"
  min_clip_sim: 0.22
  min_points: 15000
  max_points: 1200000
  min_silhouette: 0.15
  max_silhouette: 0.85

generation:
  model_variant: "sd15_text"
  seed: null
  warmup_on_start: true
  max_time_sec: 28